---
- name: install blacklist packages
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - openssh-blacklist
    - openssh-blacklist-extra
    - openssl-blacklist
    - openssl-blacklist-extra
