---
# FIXME:
# ssh-keygen -t ed25519 -f ssh_host_ed25519_key < /dev/null
# ssh-keygen -t rsa -b 4096 -f ssh_host_rsa_key < /dev/null
# HostKey /etc/ssh/ssh_host_ed25519_key
# HostKey /etc/ssh/ssh_host_rsa_key
# ssh-keygen -G "${HOME}/moduli" -b 4096
# ssh-keygen -T /etc/ssh/moduli -f "${HOME}/moduli"
# rm "${HOME}/moduli"

- name: ensure sshd_config is configured to use secure crypto
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^{{ item.key }} "
    line: "{{ item.key }} {{ item.value }}"
    state: present
  with_items:
    - key: Protocol
      value: 2
    - key: KexAlgorithms
      value: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256 
    - key: Ciphers
      value: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr }
    - key: MACs
      value: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
  register: sshd_config

- name: restart ssh if necessary
  service:
    name: ssh
    state: restarted
  when: sshd_config|changed
